---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: roshan
  become: false
  tasks:
    - name: Install Python Docker SDK
      pip:
        name: docker
        executable: pip3

    - name: Pull Docker Image
      community.docker.docker_image:
        name: "iiitbroshan/calculator"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Check if container with name 'calculator' is running
      command: docker ps -q -f name=calculator
      register: running_container
      changed_when: false
      failed_when: false

    - name: Remove the old container if it exists
      docker_container:
        name: calculator
        state: absent
      when: running_container.stdout != ""

    - name: Running container
      shell: docker run -it -d --name calculator iiitbroshan/calculator /bin/bash
