---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: abhishek
  become: false
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "abhi297/calculator"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result
        
    - name: Start Docker service
      service:
        name: docker
        state: started
        
    - name: Check if container is already running
      command: docker ps -q -f name=calculator
      register: container_status
      ignore_errors: yes

    - name: Remove existing container if running
      shell: docker rm -f calculator
      when: container_status.stdout != ""
        
    - name: Running container
      shell: docker run -it -d --name calculator abhi297/calculator /bin/bash
